// <auto-generated />
using System;
using HosDemo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HosDemo.Api.Migrations
{
    [DbContext(typeof(HosDbContext))]
    partial class HosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HosDemo.Api.Domain.DriverHosSnapshot", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Available6070")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AvailableDrivingTime")
                        .HasColumnType("numeric");

                    b.Property<int?>("AvailableHours")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AvailableOnDutyTime")
                        .HasColumnType("numeric");

                    b.Property<string>("DutyStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("DriverId", "RecordedAt");

                    b.ToTable("DriverHosSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
